const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const [,, rawPdfPath, courseArgs, titleArgs, canUseGemini] = process.argv;

let pdfPath = rawPdfPath;
let course = courseArgs || 'General';
let title = titleArgs || 'Lecture';

function out(data) { console.log(JSON.stringify(data)); }
function err(msg) { console.error(msg); }

async function run() {
  if (!pdfPath || canUseGemini === 'false' || !fs.existsSync(pdfPath)) {
    out({ success: false, quizText: '', reason: 'no_pdf_or_too_large' });
    return;
  }

  const sessionsDir = path.join(__dirname, 'sessions');
  if (!fs.existsSync(sessionsDir)) {
    out({ success: false, quizText: '', reason: 'no_sessions_directory' });
    return;
  }

  const files = fs.readdirSync(sessionsDir).filter(f => f.endsWith('.json'));
  if (files.length === 0) {
    out({ success: false, quizText: '', reason: 'no_saved_sessions' });
    return;
  }

  // Pick a random saved session account to distribute the load
  const sessionFile = path.join(sessionsDir, files[Math.floor(Math.random() * files.length)]);
  err(`🚀 Launching Playwright with session: ${path.basename(sessionFile)}`);

  let browser;
  try {
    browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
    const context = await browser.newContext({ storageState: sessionFile });
    const page = await context.newPage();

    // Prevent timeouts on slow headless runs
    page.setDefaultTimeout(60000);

    err('🌐 Navigating to Google AI Studio...');
    await page.goto('https://aistudio.google.com/app/prompts/new_chat', { waitUntil: 'domcontentloaded' });

    // Wait for the UI to load
    await page.waitForTimeout(5000);

    // 1. Upload the PDF
    err('📎 Uploading PDF...');
    // Look for the generic hidden file input that Google uses
    const fileInput = page.locator('input[type="file"]').first();
    await fileInput.setInputFiles(pdfPath);
    
    // Give it plenty of time to upload and process the document
    err('⏳ Waiting 15 seconds for upload to process...');
    await page.waitForTimeout(15000);

    const prompt = `You are an expert university educator. Read the provided lecture PDF carefully.
If the document is in Arabic, you MUST output the questions and answers in Arabic. If it's mostly English, use English.

Course: ${course}
Lecture: ${title}

Generate a quiz based ONLY on the PDF content:
- 20 Multiple Choice Questions (MCQ)
- 10 True/False Questions

Use this EXACT format, no deviations (for English - adapt similarly for Arabic):

Q1. [question text]
a) [option]
b) [option]
c) [option]
d) [option]
Correct Answer: a

TF1. [statement]
Answer: True

Rules:
- Every question must come from the PDF
- Mix difficulty: 40% easy, 40% medium, 20% hard
- Wrong MCQ options must be plausible
- Output ONLY the quiz. No intro, no summary, nothing else.`;

    // 2. Type the Prompt
    err('✍️  Entering prompt...');
    // Find the chat textarea. It usually has role="textbox" or contenteditable
    const chatInput = page.locator('textarea, [contenteditable="true"]').last();
    await chatInput.fill(prompt);
    
    // 3. Submit the prompt
    await page.waitForTimeout(1000);
    // Usually "Run" button or Enter works. We will press Enter.
    await chatInput.press('Enter');
    
    err('🧠 Waiting for Gemini to generate the quiz (30 seconds)...');
    await page.waitForTimeout(30000);

    // 4. Scrape the last message generated by the model
    // AI Studio uses specific blocks for model outputs. Generic approach:
    const messageBlocks = await page.locator('user-message, model-message, .message-content, article').all();
    if (messageBlocks.length === 0) {
       throw new Error("Could not find any message blocks in the DOM. Google UI changed.");
    }
    
    const lastMessage = messageBlocks[messageBlocks.length - 1];
    const quizText = await lastMessage.innerText();

    if (!quizText || quizText.length < 100) {
        throw new Error("Extracted text was too short or empty. UI changed or generation failed.");
    }

    err('✅ Quiz generated. Asking for YouTube query...');

    // 5. Ask for YouTube query
    const ytPrompt = "Based on the lecture PDF provided, what is the best, concise Arabic search phrase to find an educational YouTube explanation exactly for this topic? Output ONLY the search query, nothing else.";
    await chatInput.fill(ytPrompt);
    await page.waitForTimeout(1000);
    await chatInput.press('Enter');

    err('🧠 Waiting for Gemini to generate YouTube query (15 seconds)...');
    await page.waitForTimeout(15000);

    const newBlocks = await page.locator('user-message, model-message, .message-content, article').all();
    const ytLastMessage = newBlocks[newBlocks.length - 1];
    const ytQuery = (await ytLastMessage.innerText()).trim();

    out({ success: true, quizText, ytQuery, accountEmail: path.basename(sessionFile) });

  } catch (error) {
    err(`❌ Browser Automation Failed: ${error.message}`);
    out({ success: false, quizText: '', reason: 'playwright_crash: ' + error.message });
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}

run();
